feat: support dev package download

diff --git a/download b/download
--- a/download
+++ b/download
@@ -8,12 +8,13 @@ if [ ! -d "debs" ];  then
     mkdir debs
 fi
 
-SOURCE="https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc"
+# SOURCE="https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc"
 # Use the source below if you feel slow, or change it on your own.
-# SOURCE="http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/"
+SOURCE="http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/"
 
 LIBC_PREFIX="libc6_"
 LIBC_DBG_PREFIX="libc6-dbg_"
+LIBC_DEV_PREFIX="libc6-dev_"
 
 die() {
   echo >&2 $1
@@ -29,6 +30,7 @@ download_single() {
   local id=$1
   local deb_name=$LIBC_PREFIX$id.deb
   local dbg_name=$LIBC_DBG_PREFIX$id.deb
+  local dev_name=$LIBC_DEV_PREFIX$id.deb
   echo "Getting $id"
   if [ -d "libs/$id" ]; then
     die "  --> Downloaded before. Remove it to download again."
@@ -55,6 +57,29 @@ download_single() {
   mkdir libs/$id/.debug
   ./extract debs/$dbg_name libs/$id/.debug
   echo "  -> Package saved to libs/$id/.debug"
+
+  # download debug info package
+  local url="$SOURCE/$dbg_name"
+  echo "  -> Location: $url"
+  echo "  -> Downloading libc debug package"
+  wget "$url" 2>/dev/null -O debs/$dbg_name || die "Failed to download package from $url"
+  echo "  -> Extracting libc debug package"
+
+  mkdir libs/$id/.debug
+  ./extract debs/$dbg_name libs/$id/.debug
+  echo "  -> Package saved to libs/$id/.debug"
+
+  # download dev info package
+  local url="$SOURCE/$dev_name"
+  echo "  -> Location: $url"
+  echo "  -> Downloading libc dev package"
+  wget "$url" 2>/dev/null -O debs/$dev_name || die "Failed to download package from $url"
+  echo "  -> Extracting libc dev package"
+
+  mkdir libs/$id/.dev
+  ./extract debs/$dev_name libs/$id/.dev
+  echo "  -> Package saved to libs/$id/.dev"
+
 }
 
 if [[ $# != 1 ]]; then
